### ISSUE TITLE
You must install Nx to enable Storage Cache

### ISSUE THREAD

**Issue by aramfe** [bojanbass/nx-aws#439]
So I tried using the plugin, but no matter which version I use (latest, 16.2.0 or 17.0.0) I always get errors, that there is no compatibility or that nx couldn't be found. 

That's my package.json

```
"dependencies": {
    "@nx-aws-plugin/nx-aws-cache": "^3.1.0",
    "@nx/devkit": "16.2.1",
    "nx": "16.2.1"
  },
```
  
  Running `yarn nx generate @nx-aws-plugin/nx-aws-cache:init --verbose` gives the following output:
```
  
✔ AWS Access Key Id · 
✔ AWS Secret Access Key · 
✔ AWS configuration profile to use · 
✔ AWS Endpoint of the web service if a custom endpoint is needed (e.g. when using MinIO) · 
✔ AWS region to which this client will send requests · us-east-1
✔ AWS S3 Bucket, where the cached Nx outputs will be stored · nx-rempte-cache.myblubilub.com
✔ Whether to force path style URLs for S3 objects (e.g. when using MinIO) (y/N) · false

Error: You must install Nx to enable Storage Cache
    at isCompatibleVersion (/Users/blabliblub/projects/myproject/node_modules/@nx-aws-plugin/nx-aws-cache/src/generators/init/generator.js:10:15)
    at /Users/blabliblub/projects/myproject/node_modules/@nx-aws-plugin/nx-aws-cache/src/generators/init/generator.js:42:14
    at Generator.next (<anonymous>)
    at /Users/blabliblub/projects/myproject/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/blabliblub/projects/myproject/node_modules/tslib/tslib.js:163:16)
    at default_1 (/Users/blabliblub/projects/myproject/node_modules/@nx-aws-plugin/nx-aws-cache/src/generators/init/generator.js:41:20)
    at Object.<anonymous> (/Users/blabliblub/projects/myproject/node_modules/nx/src/command-line/generate/generate.js:250:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/blabliblub/projects/myproject/node_modules/tslib/tslib.js:164:62)
    
```
Any ideas or which versions are compatible with this?

**Comment by zachdixon** [comment]
I just ran into this as well and fixed it by installing `@nx/workspace`

**Comment by bojanbass** [comment]
I think this shouldn't be an issue. As far as I know, every time a new NX workspace is created, `@nx/workspace` is added by default.
